[package]
name = "remnantsofsiren/replicator2"
version = "2.0.1-experimental"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "Packages", "build", "test.project.json", "selene.toml", "README.md", ".gitignore", ".vscode", ".github", "NetDefinitions.blink", "oldsrc"]


[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Sift = "csqrl/sift@^0"
Trove = "sleitnick/trove@^1"
Signal = "data-oriented-house/lemonsignal@^1"